package models

import "testing"

func TestLibraryCollectionAllowsAutomaticPoster(t *testing.T) {
	tests := []struct {
		name       string
		collection *LibraryCollection
		want       bool
	}{
		{name: "nil collection", collection: nil, want: false},
		{name: "empty unsuppressed poster", collection: &LibraryCollection{}, want: true},
		{name: "existing generated poster", collection: &LibraryCollection{PosterURL: "generated.webp", PosterAutoGenerated: true}, want: true},
		{name: "existing custom poster", collection: &LibraryCollection{PosterURL: "custom.webp"}, want: false},
		{name: "suppressed empty poster", collection: &LibraryCollection{PosterSuppressed: true}, want: false},
		{name: "suppressed generated poster", collection: &LibraryCollection{PosterURL: "generated.webp", PosterAutoGenerated: true, PosterSuppressed: true}, want: false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := tt.collection.AllowsAutomaticPoster(); got != tt.want {
				t.Fatalf("AllowsAutomaticPoster() = %t, want %t", got, tt.want)
			}
		})
	}
}
